# Generated by Django 5.2 on 2025-04-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0002_alter_artist_nationality'),
        ('genres', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('artists', models.ManyToManyField(related_name='songs', to='artists.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='genres.genre')),
            ],
        ),
    ]
